@host = http://localhost:3000


###### API POSTS
GET {{host}}/api/posts
###
GET  {{host}}/api/posts/8
###
GET {{host}}/api/posts/autor/20
###
POST {{host}}/api/posts
Content-Type: application/json

{
    "titulo": "Cómo preparar una cena romántica",
    "descripcion": "¿Quieres sorprender a tu pareja con una cena romántica? Aprende cómo preparar el ambiente adecuado y un delicioso menú que conquiste su corazón.",
    "categoria": "Cocina",
    "autor_idautor": 17
}
###
PUT {{host}}/api/posts
Content-Type: application/json

{
    
}
###
DELETE {{host}}/api/posts


###### API AUTORES
GET {{host}}/api/autores
###
GET {{host}}/api/autores/20
###
POST {{host}}/api/autores
Content-Type: application/json

{
    "nombre": "Daniel Perez",
    "email": "danielperez@example.com",
    "imagen": "https://example.com/imagen21.jpg"
}
###
PUT {{host}}/api/autores/20
Content-Type: application/json

{
    "nombre": "Daniel Rodriguez",
    "email": "danielrodriguez@example.com",
    "imagen": "https://example.com/imagen20.jpg"
}
###
DELETE {{host}}/api/autores/20
